### ISSUE TITLE
Failing Tests TestGenerateCodePutDepPackage in Codegen_test.go

### ISSUE THREAD

**Issue by nofun97** [anz-bank/sysl#396]
### Problem
There's a possible race conditions on two tests, as they only fail sometimes when integrations tests are run. The functions are `TestGenerateCodePutDepPackageInCommentUsingLists` and `TestGenerateCodePutDepPackageAndParamTypeInComment`.

It might be due to running the tests in parallel as the tests use the same files.

Error:
```
--- FAIL: TestGenerateCodePutDepPackageInCommentUsingLists (0.17s)
    Codegen_test.go:191:
        	Error Trace:	Codegen_test.go:191
        	Error:      	"[[] []]" should have 1 item(s), but has 2
        	Test:       	TestGenerateCodePutDepPackageInCommentUsingLists
    Codegen_test.go:197:
        	Error Trace:	Codegen_test.go:197
        	Error:      	Not equal:
        	            	expected: "dep,dep"
        	            	actual  : ""

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-dep,dep
        	            	+
        	Test:       	TestGenerateCodePutDepPackageInCommentUsingLists
time="2019-11-11T17:34:49+11:00" level=warning msg="Field \"customers\" (type \"Address\") refers to type list of Customer in app \"ObjectModel\""
--- FAIL: TestGenerateCodePutDepPackageAndParamTypeInComment (0.20s)
    Codegen_test.go:145:
        	Error Trace:	Codegen_test.go:145
        	Error:      	"[[] []]" should have 1 item(s), but has 2
        	Test:       	TestGenerateCodePutDepPackageAndParamTypeInComment
    Codegen_test.go:151:
        	Error Trace:	Codegen_test.go:151
        	Error:      	Not equal:
        	            	expected: "dep.GET /dep/{id},dep.GET /moredep/{id}"
        	            	actual  : ""

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-dep.GET /dep/{id},dep.GET /moredep/{id}
        	            	+
        	Test:       	TestGenerateCodePutDepPackageAndParamTypeInComment
```

changes from #392

**Comment by anzdaddy** [comment]
Reading the same files concurrently shouldn't be a problem. Writing the same files shouldn't be a problem either, since GenerateCodeWithParams since WriteToMemOverlayFs diverts all writes to a memory fs.

**Comment by nofun97** [comment]
Running this 1000 times with
```bash
for i in {1..1000}; do go test ./... ; done
```
shows that another test fails
```
--- FAIL: TestGenerateCodePutDepPackageInCommentUsingSets (0.13s)
    Codegen_test.go:167:
        	Error Trace:	Codegen_test.go:167
        	Error:      	"[]" should have 2 item(s), but has 0
        	Test:       	TestGenerateCodePutDepPackageInCommentUsingSets
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 66 [running]:
testing.tRunner.func1(0xc000322100)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x197ef60, 0x261d9e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/anz-bank/sysl/sysl2/sysl.TestGenerateCodePutDepPackageInCommentUsingSets(0xc000322100)
	/Users/allanadn/work/github.com/anz-bank/sysl/sysl2/sysl/Codegen_test.go:170 +0x5e9
testing.tRunner(0xc000322100, 0x1af0750)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
```

Commenting out `t.Parallel()` in all three tests do not help as it reproduces the same errors. Each test only appears some times.

Tests have failed in other appveyor builds in other branches:
* https://ci.appveyor.com/project/anz-bank/sysl/builds/28789324
* https://ci.appveyor.com/project/anz-bank/sysl/builds/28798122
* https://ci.appveyor.com/project/anz-bank/sysl/builds/28789236

**Comment by anz-gordonj7** [comment]
OK, the ACTUAL issue here is that the codegen tests call LoadSyslModule() which returns the "default" app name, which is only correct if there is only one app, this is clearly wrong in a few tests! that API probably needs to be changed (and a better way to get the correct default app name added)
